# Site settings
title: "Jay Hollinsworth Portfolio"
email: jhollinsworth@gmail.com
description: The portfolio site of Jay Hollinsworth, Designer of user interfaces, motion graphics, and print materials
baseurl: "/Hollinsworth_portfolio-site" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
facebook_username: jhollinsworth
twitter_username: JayHollinsworth
instagram_username: jayhollinsworth
dribbble_username: jhollinsworth
vimeo_username: hollinsworth

# Build settings
markdown: kramdown
